# Generated by Django 2.1.15 on 2021-03-21 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(default='', max_length=100)),
                ('accords_proche', models.ManyToManyField(blank=True, related_name='_accord_accords_proche_+', to='bot.Accord')),
            ],
            options={
                'verbose_name': 'Accord',
                'verbose_name_plural': 'Accords',
                'ordering': ['nom'],
            },
        ),
    ]
